### ISSUE TITLE
[Security] Characters in username

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-workplace#113]
Character length
Choose a username 6–30 characters long. Your username can be any combination of letters, numbers, or symbols.

Special characters
Usernames can contain letters (a-z), numbers (0-9), and periods (.).
Usernames cannot contain an ampersand (&), equals sign (=), underscore (_), apostrophe ('), dash (-), plus sign (+), comma (,), brackets (<,>), or more than one period (.) in a row.

**Comment by chibenwa** [comment]
Let's disallow also space, enter and non visible characters.
Can I be allowed to use non ascii characters like UTF-8?
Emojis?

**Comment by chibenwa** [comment]
If we use username as an email local part we would be best served by [a-z][A-Z][0-9]_-. with no more than two consecutive special character, not starting  by a number/special character, not ending with a special character.

**Comment by shepilov** [comment]
@chibenwa Yes, no emojis and none ascii, only:
>>Usernames can contain letters (a-z), numbers (0-9), and periods (.).

We can add an underscore, but I'm not sure about a dash
