### ISSUE TITLE
Wrong error message when using dummy phone numbers

### ISSUE THREAD

**Issue by tk-nguyen** [linagora/twake-workplace#114]
When registering using a fake phone number, the UI always returns `Number is already registered`:

![image](https://github.com/linagora/twake-workplace/assets/39090621/dfcea768-825a-4e7b-8f69-bb033f985ef2)

The `check-phone` endpoint is returning 500 with `failed to check phone` error:

<img width="1290" alt="image" src="https://github.com/linagora/twake-workplace/assets/39090621/67dc6bf3-9a9b-4068-a82e-323cdb63dd88">

The app logs are returning `Invalid phone`:

<img width="1097" alt="image" src="https://github.com/linagora/twake-workplace/assets/39090621/0ddce61e-e842-4f57-869f-2b42ae52391e">

**Comment by rezk2ll** [comment]
fixed in https://github.com/linagora/twake-workplace/pull/115
