### ISSUE TITLE
[Bug] Cannot log into products with created credentials

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-workplace#117]
Environment: https://sign-up.stg.lin-saas.com

1. Sign up 
2. Follow until the 'Success' screen 
3. Click on the products 
4. Can't log in 

https://github.com/linagora/twake-workplace/assets/97684890/8af023cb-7b57-4feb-be0f-cc70a46c09f4

https://github.com/linagora/twake-workplace/assets/97684890/a8209f3f-7381-4968-a412-74a7ea7f6c2c

**Comment by tprudentova** [comment]
It seems to be good for Chat and Drive, but I still cannot log into mail ("Bad credentials")


https://github.com/linagora/twake-workplace/assets/97684890/c93f02e9-1dfc-4753-910d-f607feb3aba8

**Comment by tprudentova** [comment]
The Twake Mail bug seems to happen with Safari only

**Comment by rezk2ll** [comment]
this is fixed and tested on tmail side
