### ISSUE TITLE
On 1st login user needs to enter Matrix ID (username) manually

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-workplace#131]
1. Create an account 
2. On the page with apps select some product
3. The Matrix page opens, you need to enter your Matrix ID manually 

Expectation: best scenario: user doesn’t see this page at all. Tolerable scenario: the ID is pre-filled

https://github.com/linagora/twake-workplace/assets/97684890/14862881-88b2-4626-9d81-1ddaa5379cb3

**Comment by shepilov** [comment]
@hoangdat could you please link to the relevant twake chat issue

**Comment by hoangdat** [comment]
Why it is done? any PR link to this?

**Comment by guimard** [comment]
Just a Synapse config parameter
