### ISSUE TITLE
[Bug] I cannot receive an SMS with code for sign up

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-workplace#150]
Tried with several Russian numbers, maybe it's better for other countries?

**Comment by Arsnael** [comment]
@tprudentova Same for Vietnam.

I know that Vietnam strictly restrict and filter out sms coming from outside of the country for multiple (not always clear reasons)

Would guess the same for Russia, specially with what's going on overall. Something that needs to be worked on with the sms provider linagora chose for sms delivery I guess

**Comment by guimard** [comment]
Hi, for now we disabled SMS sent for staging platform. Simply use the "magic" code to register (see Signal channel)
