### ISSUE TITLE
[Bug] Limitation of symbols in the username

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-workplace#151]
When I select a username, I cannot use one that is shorter than 6 symbols. Seems a bit too much. I would go with >2. 

<img width="1280" alt="Screenshot 2024-05-13 at 15 25 40" src="https://github.com/linagora/twake-workplace/assets/97684890/2d973ef3-7529-423e-a2b4-0d2e508d863e">

**Comment by rezk2ll** [comment]
hello @tprudentova 

this limitation is discussed in https://github.com/linagora/twake-workplace/issues/113

- username should be 6–30 characters long. 
- username can be any combination of letters, numbers, or symbols.

also https://github.com/linagora/twake-workplace/issues/113#issuecomment-2035487640

**Comment by tprudentova** [comment]
I see, I see. @shepilov was there some particular reason for such limitation? Seems not very user-friendly

**Comment by tprudentova** [comment]
Please, make the limitation "not shorter than 3 symbols". Discussed with Anton
