### ISSUE TITLE
[Bug] Redirection problems

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-workplace#177]
Google Chrome

# Case 1

1. I open https://sign-up.stg.lin-saas.com/?post_registered_redirect_url=https://tmail.stg.lin-saas.com/&app=tmail
2. I sign up 
3. I'm not logged into TMail after redirect

https://github.com/linagora/twake-workplace/assets/97684890/80be8fce-1d26-4e3d-b3b2-9d8274c0cf58

# Case 2

1. I open https://sign-up.stg.lin-saas.com/?post_registered_redirect_url=https://chat.stg.lin-saas.com/&app=chat
2. I sign up 
3. I'm caught in an infinite loop of the greeting screen 

https://github.com/linagora/twake-workplace/assets/97684890/67150347-3fa4-438c-acbb-5b15362db695

All good with Drive though!

**Comment by rezk2ll** [comment]
hi @tprudentova, for the first cast it's a typo in the URL: it should be mail instead of tmail ( I fixed it now in notion )

so the correct URL is:  https://sign-up.stg.lin-saas.com/?post_registered_redirect_url=https://mail.stg.lin-saas.com/&app=tmail

for the second case ( chat ) it's already fixed in #178

**Comment by tprudentova** [comment]
Hi @rezk2ll ! 

The problem persists (but so do we) 

Case 1: 

I follow the link from Chat landing. After sign-in/sign-up I should be logged into Twake Chat automatically (without the greeting screen)


https://github.com/linagora/twake-workplace/assets/97684890/bc449b80-faa6-49b7-afef-cf356bb5878e

Case 2: 

I follow the link from Mail landing. After sign-in/sign-up I should be logged into Twake Mail automatically (without the greeting screen)


https://github.com/linagora/twake-workplace/assets/97684890/f2305906-0dcf-4864-8ed0-b49fb1869296

**Comment by tprudentova** [comment]
(Same for Drive)

**Comment by rezk2ll** [comment]
@tprudentova I see the desired outcome now:
if I intend to register ( use the sign-up URL) but instead I log in / already logged in I should just get redirected to the product.

currently, we distinguish login and registration attempts using query parameters `post_registrered_redirect_url` and `post_login_redirect_url`.

**Comment by rezk2ll** [comment]
@tprudentova it is fixed now
