### ISSUE TITLE
[Bug] Bad layout on some screens 

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-workplace#185]
![photo_2024-05-22_09-46-44](https://github.com/linagora/twake-workplace/assets/97684890/c78fdf71-e0df-4499-9ce1-2a345e3a7cff)

**Comment by rezk2ll** [comment]
Hello @tprudentova, is the current design of the success page final?
is there a plan to replace it with an improved version later on?

**Comment by tprudentova** [comment]
@rezk2ll hi! It's generally final, yes. We only need to change logos to the new ones

https://www.figma.com/design/Cu4NB44bcURKEy40DEfwWi/Design-system-1.0?node-id=56879-7309&t=D5AhNKeGwTj4BY6G-0

**Comment by rezk2ll** [comment]
@tprudentova  updated in https://github.com/linagora/twake-workplace/pull/203
will add remaining icons once bobs adds them
