### ISSUE TITLE
[SIGNIN] Footer is not correct as figma

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-workplace#19]
OS: WEB only 
Browser: - Chrome
Device: Laptop

### **Reproduce Step:** 
1, User access to: Twake registration
2, User select sigin tab

### **Actual:** 
- Existed © 2000-2023, LINAGORA at footer
### **Expected:** 
- Dont have © 2000-2023, LINAGORA

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/0fafc9cc-43ab-4cba-8729-e4fc1da2869d)

**Comment by rezk2ll** [comment]
i don't think that we show the copyright when registering and when we switch tabs we should hide it.

what do you think @shepilov ?
