### ISSUE TITLE
[SIGNIN] Recovery Password is not working

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-workplace#20]
OS: WEB only 
Browser: - Chrome
Device: Laptop

### **Reproduce Step:** 
1, User access to: Twake registration
2, User select sigin tab
3, User click on Recovery Password

### **Actual:** 
- Nothing happen

### **Expected:** 
- Can recovery password

**Comment by rezk2ll** [comment]
added in https://github.com/linagora/twake-workplace/pull/96
