### ISSUE TITLE
[Bug] Wrong redirection for sign-up from mobile app

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-workplace#208]
Current behaviour: 
Open Twake Chat app -> Click Create Twake ID -> Twake Workplace sign-up is opened -> Create ID -> Redirection back to the app, user isn't signed in 

Expected behaviour: 
Open Twake Chat app -> Click Create Twake ID -> **Twake Chat** sign-up is opened -> Create ID -> Redirection back to the app, **user is signed in automatically**

https://github.com/linagora/twake-workplace/assets/97684890/6156fcab-5c52-4a01-a7f6-7d4f93a74afa

**Comment by rezk2ll** [comment]
@tprudentova is this still the case?

**Comment by tprudentova** [comment]
Nope, I think we can close it
