### ISSUE TITLE
[Bug] [CHAT] Need to perform an additional step to sign up

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-workplace#217]
When I'm inside the app and click Create Twake ID, I'm redirected to a web page where I need to click Create Twake ID one more time 

https://github.com/linagora/twake-workplace/assets/97684890/b268738e-8075-4bdc-8fd1-651b91a97241

**Comment by rezk2ll** [comment]
@tprudentova can you copy the link of the page that is displayed after clicking on the button in the mobile app?
![image](https://github.com/linagora/twake-workplace/assets/6764881/6c71195f-bd35-4c12-9e57-23d0338a9a9e)
