### ISSUE TITLE
[Bug] Cannot use any keyboard except for Latin 

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-workplace#77]
1. Go to https://register.tom-dev.xyz
2. Enter phone number
3. Enter code
4. Enter username 
5. Enter name and surname using, for instance, Russian keyboard (Иван Иванов)
6. Cannot go to the next screen 

Expectation: I can use any symbols for Name and Surname fields

https://github.com/linagora/twake-workplace/assets/97684890/ad33bf30-70b8-41a4-8b65-55c8227d1cd0

**Comment by tprudentova** [comment]
@rezk2ll the bug still happens :(

https://github.com/linagora/twake-workplace/assets/97684890/c41a0cec-64d8-425c-81de-2ecf610de9f4

**Comment by rezk2ll** [comment]
@tprudentova done, fixed and deployed now
