### ISSUE TITLE
Wrong translates on Public Platform

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-workplace#90]
### Decs

![Image](https://github.com/linagora/twake-workplace/assets/99852347/c4e703d3-ab89-4e53-bda6-6b1566043645)

**Comment by rezk2ll** [comment]
@nqhhdev what is the correct VN translation for the first name field?

also the project is hosted on webplate https://hosted.weblate.org/projects/linagora/twake-workplace/

**Comment by rezk2ll** [comment]
@nqhhdev can i close the issue?
