### ISSUE TITLE
Wrong callback when sign up successfully

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-workplace#99]
### Reproduce steps:
- Domain: localhost

https://github.com/linagora/twake-workplace/assets/99852347/c9f1e76d-e72f-4daf-a774-06d882c6bdf1

cc: @hoangdat

**Comment by rezk2ll** [comment]
hello @nqhhdev
what is the expected result in this case?

also when choosing a product from the success page, the twake chat url is preconfigured in an ENV variables 

```bash
PUBLIC_TWAKE_WEB="https://beta.twake.app/"
```

**Comment by hoangdat** [comment]
hi @rezk2ll , we are working on client side, we have a lot of domains for client side (`localhost:xxxx`), what is the best way to make it flexible for dev?

**Comment by shepilov** [comment]
@hoangdat is it still relevant?
